platform: mac
language: swedish

speech_to_text:
    whisper_model: small
    wake_word: "Hej Lundin"
    similarity_score: 0.75
    record_timeout: 5
    energy_threshold: 300

language_model:
    model: gpt-3.5-turbo