platform: linux_arm64
# Choose platform in the following way:
# If using M1 or M2 or M* Mac: mac_arm
# If using mac with intel or amd cpu: mac_amd
# If using RPI 4 or below: linux_arm32
# If using RPI 5 or above: linux_arm64
# If using linux with intel or amd cpu: linux_amd
# If using windows: Currently not supported.
language: swedish # Make sure this matches your tts model.

error_message: "Hoppsan, där gick något fel."

speech_to_text:
    whisper_model: small
    wake_word: "Erik"
    similarity_score: 0.75 # Determines how close wake word needs to be to your word.

    whisper_cpp:
        length: 10000
        capture_device: 0 # capture device ID. Change if using other
        n_threads: 3 # threads to use
        audio_context_len: 512 # audio context size (0 - all)
        vad_thold: 0.6 # voice activity detection threshold
        file_path: ../data/transcription.txt # don't change this :)

language_model:
    model: gpt-3.5-turbo
    extra_instructions: Always answer in Swedish.

text_to_speech:
    binary_path: bin # relative path to where piper is installed
    piper_tts_release_url: https://github.com/rhasspy/piper/releases/download/2023.11.14-2/
    binary_download_files:
        mac_arm: piper_macos_x64.tar.gz # If using amd64 cpu on mac, change this
        mac_amd: piper_macos_x64.tar.gz
        linux_arm32: piper_linux_armv7l.tar.gz
        linux_arm64: piper_linux_aarch64.tar.gz
        linux_amd: piper_linux_x86_64.tar.gz

    piper_voice:
        # You can find available voices at https://huggingface.co/rhasspy/piper-voices/tree/v1.0.0
        # Or you can create your own :)
        model_file_name: erkvoice-medium.onnx
        weights_url: https://huggingface.co/snigelnmjau/erkvoice/resolve/main/model_22.onnx?download=true
        config_url: https://huggingface.co/snigelnmjau/erkvoice/resolve/main/model_22.onnx.json?download=true

smart_home:
    dirigera:
        rooms: ["hall", "sovrum", "kök", "vardagsrum"]
# Possible to list names of both rooms and individual lights here. TODO separate

    default_spotify_device: Denon CEOL piccolo
