OPENAI_API_KEY = "OPENAI_API_KEY"
OPENAI_ORGANIZATION = "OPENAI_ORGANIZATION"

DIRIGERA_TOKEN = "DIRIGERA_TOKEN"
DIRIGERA_IP = "DIRIGERA_IP"

SPOTIFY_CLIENT_ID="SPOTIFY_CLIENT_ID"
SPOTIFY_CLIENT_SECRET="SPOTIFY_CLIENT_SECRET"
SPOTIFY_REDIRECT_URL="SPOTIFY_REDIRECT_URL"
AMPLIFIER_IP="AMPLIFIER_IP"

HOME_LAT="HOME_LAT"
HOME_LON="HOME_LON"